services:
  form-forwarder:
    container_name: form-forwarder
    image: outfortheseason/form-forwarder
    ports:
      - 7070:7070
    restart: unless-stopped
    env_file:
      - .env
    build: .
